name: freedomtolive
favicon: null
layout_spectrum: 0.25401899102143943
typography_spectrum: 0.8410196171607822
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.005106016295030713
  lightness: 0.36166801559738815
  saturation: 0.6843784188386053
  rhythmicContrast: 0.6294421181082726
purpose: []
